package com.muze.core.app.hforder.model;


import com.muze.core.app.utils.excel.annotation.ExcelField;

import java.util.Date;
import java.util.List;

public class HfOrder {

    private String errorType;
    private String successPayTimeFrom;
    private String successPayTimeto;
    private  String contractNumbe;

    public String getErrorType() {
        return errorType;
    }

    public void setErrorType(String errorType) {
        this.errorType = errorType;
    }

    public String getSuccessPayTimeFrom() {
        return successPayTimeFrom;
    }

    public void setSuccessPayTimeFrom(String successPayTimeFrom) {
        this.successPayTimeFrom = successPayTimeFrom;
    }

    public String getSuccessPayTimeto() {
        return successPayTimeto;
    }

    public void setSuccessPayTimeto(String successPayTimeto) {
        this.successPayTimeto = successPayTimeto;
    }

    public String getContractNumbe() {
        return contractNumbe;
    }

    public void setContractNumbe(String contractNumbe) {
        this.contractNumbe = contractNumbe;
    }

    private String jump;

    public String getJump() {
        return jump;
    }

    public void setJump(String jump) {
        this.jump = jump;
    }

    public List<String> getDocids() {
        return docids;
    }

    public void setDocids(List<String> docids) {
        this.docids = docids;
    }

    private String hforderisme;

    public String getHforderisme() {
        return hforderisme;
    }

    public void setHforderisme(String hforderisme) {
        this.hforderisme = hforderisme;
    }

    private List<String> docids;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_order.id
     *
     * @mbggenerated
     */
    @ExcelField(title = "当前id")
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_order.doc_id
     *
     * @mbggenerated
     */
    private String docId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_order.student_id
     *
     * @mbggenerated
     */
    private String studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_order.student_name
     *
     * @mbggenerated
     */
    private String studentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_order.gaokao_year
     *
     * @mbggenerated
     */
    private Date gaokaoYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_order.love_subject
     *
     * @mbggenerated
     */
    private String loveSubject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_order.channel
     *
     * @mbggenerated
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_order.if_listener
     *
     * @mbggenerated
     */
    private Boolean ifListener;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_order.if_success
     *
     * @mbggenerated
     */
    private Boolean ifSuccess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_order.if_error
     *
     * @mbggenerated
     */
    private Boolean ifError;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_order.if_introduction
     *
     * @mbggenerated
     */
    private Boolean ifIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_order.introduction_type
     *
     * @mbggenerated
     */
    private String introductionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_order.introduction_id
     *
     * @mbggenerated
     */
    private String introductionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_order.u_time
     *
     * @mbggenerated
     */
    private Date uTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_order.c_time
     *
     * @mbggenerated
     */
    private Date cTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_order.backup
     *
     * @mbggenerated
     */
    private String backup;


    private String  studentPhone;

    private String  orgName;
    private String  docName;

    private String ctime_from;
    private String ctime_to;

    private String listentime_from;
    private String listentime_to;

    public String getListentime_from() {
        return listentime_from;
    }

    public void setListentime_from(String listentime_from) {
        this.listentime_from = listentime_from;
    }

    public String getListentime_to() {
        return listentime_to;
    }

    public void setListentime_to(String listentime_to) {
        this.listentime_to = listentime_to;
    }

    public String getCtime_from() {
        return ctime_from;
    }

    public void setCtime_from(String ctime_from) {
        this.ctime_from = ctime_from;
    }

    public String getCtime_to() {
        return ctime_to;
    }

    public void setCtime_to(String ctime_to) {
        this.ctime_to = ctime_to;
    }

    public String getOrgName() {
        return orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    public String getDocName() {
        return docName;
    }

    public void setDocName(String docName) {
        this.docName = docName;
    }

    public String getStudentPhone() {
        return studentPhone;
    }

    public void setStudentPhone(String studentPhone) {
        this.studentPhone = studentPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_order.id
     *
     * @return the value of hf_order.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_order.id
     *
     * @param id the value for hf_order.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_order.doc_id
     *
     * @return the value of hf_order.doc_id
     *
     * @mbggenerated
     */
    public String getDocId() {
        return docId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_order.doc_id
     *
     * @param docId the value for hf_order.doc_id
     *
     * @mbggenerated
     */
    public void setDocId(String docId) {
        this.docId = docId == null ? null : docId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_order.student_id
     *
     * @return the value of hf_order.student_id
     *
     * @mbggenerated
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_order.student_id
     *
     * @param studentId the value for hf_order.student_id
     *
     * @mbggenerated
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_order.student_name
     *
     * @return the value of hf_order.student_name
     *
     * @mbggenerated
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_order.student_name
     *
     * @param studentName the value for hf_order.student_name
     *
     * @mbggenerated
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_order.gaokao_year
     *
     * @return the value of hf_order.gaokao_year
     *
     * @mbggenerated
     */
    public Date getGaokaoYear() {
        return gaokaoYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_order.gaokao_year
     *
     * @param gaokaoYear the value for hf_order.gaokao_year
     *
     * @mbggenerated
     */
    public void setGaokaoYear(Date gaokaoYear) {
        this.gaokaoYear = gaokaoYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_order.love_subject
     *
     * @return the value of hf_order.love_subject
     *
     * @mbggenerated
     */
    public String getLoveSubject() {
        return loveSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_order.love_subject
     *
     * @param loveSubject the value for hf_order.love_subject
     *
     * @mbggenerated
     */
    public void setLoveSubject(String loveSubject) {
        this.loveSubject = loveSubject == null ? null : loveSubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_order.channel
     *
     * @return the value of hf_order.channel
     *
     * @mbggenerated
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_order.channel
     *
     * @param channel the value for hf_order.channel
     *
     * @mbggenerated
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_order.if_listener
     *
     * @return the value of hf_order.if_listener
     *
     * @mbggenerated
     */
    public Boolean getIfListener() {
        return ifListener;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_order.if_listener
     *
     * @param ifListener the value for hf_order.if_listener
     *
     * @mbggenerated
     */
    public void setIfListener(Boolean ifListener) {
        this.ifListener = ifListener;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_order.if_success
     *
     * @return the value of hf_order.if_success
     *
     * @mbggenerated
     */
    public Boolean getIfSuccess() {
        return ifSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_order.if_success
     *
     * @param ifSuccess the value for hf_order.if_success
     *
     * @mbggenerated
     */
    public void setIfSuccess(Boolean ifSuccess) {
        this.ifSuccess = ifSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_order.if_error
     *
     * @return the value of hf_order.if_error
     *
     * @mbggenerated
     */
    public Boolean getIfError() {
        return ifError;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_order.if_error
     *
     * @param ifError the value for hf_order.if_error
     *
     * @mbggenerated
     */
    public void setIfError(Boolean ifError) {
        this.ifError = ifError;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_order.if_introduction
     *
     * @return the value of hf_order.if_introduction
     *
     * @mbggenerated
     */
    public Boolean getIfIntroduction() {
        return ifIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_order.if_introduction
     *
     * @param ifIntroduction the value for hf_order.if_introduction
     *
     * @mbggenerated
     */
    public void setIfIntroduction(Boolean ifIntroduction) {
        this.ifIntroduction = ifIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_order.introduction_type
     *
     * @return the value of hf_order.introduction_type
     *
     * @mbggenerated
     */
    public String getIntroductionType() {
        return introductionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_order.introduction_type
     *
     * @param introductionType the value for hf_order.introduction_type
     *
     * @mbggenerated
     */
    public void setIntroductionType(String introductionType) {
        this.introductionType = introductionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_order.introduction_id
     *
     * @return the value of hf_order.introduction_id
     *
     * @mbggenerated
     */
    public String getIntroductionId() {
        return introductionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_order.introduction_id
     *
     * @param introductionId the value for hf_order.introduction_id
     *
     * @mbggenerated
     */
    public void setIntroductionId(String introductionId) {
        this.introductionId = introductionId == null ? null : introductionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_order.u_time
     *
     * @return the value of hf_order.u_time
     *
     * @mbggenerated
     */
    public Date getuTime() {
        return uTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_order.u_time
     *
     * @param uTime the value for hf_order.u_time
     *
     * @mbggenerated
     */
    public void setuTime(Date uTime) {
        this.uTime = uTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_order.c_time
     *
     * @return the value of hf_order.c_time
     *
     * @mbggenerated
     */
    public Date getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_order.c_time
     *
     * @param cTime the value for hf_order.c_time
     *
     * @mbggenerated
     */
    public void setcTime(Date cTime) {
        this.cTime = cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_order.backup
     *
     * @return the value of hf_order.backup
     *
     * @mbggenerated
     */
    public String getBackup() {
        return backup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_order.backup
     *
     * @param backup the value for hf_order.backup
     *
     * @mbggenerated
     */
    public void setBackup(String backup) {
        this.backup = backup == null ? null : backup.trim();
    }
}