package com.muze.core.app.task.model;

import java.util.Date;

public class QuartzLogModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_log.task_id
     *
     * @mbggenerated
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_log.task_name
     *
     * @mbggenerated
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_log.task_begin_time
     *
     * @mbggenerated
     */
    private String taskBeginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_log.task_end_time
     *
     * @mbggenerated
     */
    private String taskEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_log.task_result
     *
     * @mbggenerated
     */
    private String taskResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_log.task_running_message
     *
     * @mbggenerated
     */
    private String taskRunningMessage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_log.id
     *
     * @return the value of qrtz_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_log.id
     *
     * @param id the value for qrtz_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_log.task_id
     *
     * @return the value of qrtz_log.task_id
     *
     * @mbggenerated
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_log.task_id
     *
     * @param taskId the value for qrtz_log.task_id
     *
     * @mbggenerated
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_log.task_name
     *
     * @return the value of qrtz_log.task_name
     *
     * @mbggenerated
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_log.task_name
     *
     * @param taskName the value for qrtz_log.task_name
     *
     * @mbggenerated
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_log.task_begin_time
     *
     * @return the value of qrtz_log.task_begin_time
     *
     * @mbggenerated
     */
    public String getTaskBeginTime() {
        return taskBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_log.task_begin_time
     *
     * @param taskBeginTime the value for qrtz_log.task_begin_time
     *
     * @mbggenerated
     */
    public void setTaskBeginTime(String taskBeginTime) {
        this.taskBeginTime = taskBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_log.task_end_time
     *
     * @return the value of qrtz_log.task_end_time
     *
     * @mbggenerated
     */
    public String getTaskEndTime() {
        return taskEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_log.task_end_time
     *
     * @param taskEndTime the value for qrtz_log.task_end_time
     *
     * @mbggenerated
     */
    public void setTaskEndTime(String taskEndTime) {
        this.taskEndTime = taskEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_log.task_result
     *
     * @return the value of qrtz_log.task_result
     *
     * @mbggenerated
     */
    public String getTaskResult() {
        return taskResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_log.task_result
     *
     * @param taskResult the value for qrtz_log.task_result
     *
     * @mbggenerated
     */
    public void setTaskResult(String taskResult) {
        this.taskResult = taskResult == null ? null : taskResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_log.task_running_message
     *
     * @return the value of qrtz_log.task_running_message
     *
     * @mbggenerated
     */
    public String getTaskRunningMessage() {
        return taskRunningMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_log.task_running_message
     *
     * @param taskRunningMessage the value for qrtz_log.task_running_message
     *
     * @mbggenerated
     */
    public void setTaskRunningMessage(String taskRunningMessage) {
        this.taskRunningMessage = taskRunningMessage == null ? null : taskRunningMessage.trim();
    }
}