package com.muze.core.app.hferror.model;

import java.util.Date;

public class HfOrderError {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_order_error.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_order_error.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_order_error.error_id
     *
     * @mbggenerated
     */
    private Integer errorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_order_error.c_time
     *
     * @mbggenerated
     */
    private Date cTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_order_error.id
     *
     * @return the value of hf_order_error.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_order_error.id
     *
     * @param id the value for hf_order_error.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_order_error.order_id
     *
     * @return the value of hf_order_error.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_order_error.order_id
     *
     * @param orderId the value for hf_order_error.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_order_error.error_id
     *
     * @return the value of hf_order_error.error_id
     *
     * @mbggenerated
     */
    public Integer getErrorId() {
        return errorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_order_error.error_id
     *
     * @param errorId the value for hf_order_error.error_id
     *
     * @mbggenerated
     */
    public void setErrorId(Integer errorId) {
        this.errorId = errorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_order_error.c_time
     *
     * @return the value of hf_order_error.c_time
     *
     * @mbggenerated
     */
    public Date getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_order_error.c_time
     *
     * @param cTime the value for hf_order_error.c_time
     *
     * @mbggenerated
     */
    public void setcTime(Date cTime) {
        this.cTime = cTime;
    }
}