package com.muze.core.app.hfsucess.model;

import com.muze.core.app.hforder.model.HfOrder;

import java.math.BigDecimal;
import java.util.Date;

public class HfSuccess {

    private HfOrder hfOrder;

    public HfOrder getHfOrder() {
        return hfOrder;
    }

    public void setHfOrder(HfOrder hfOrder) {
        this.hfOrder = hfOrder;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_success.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_success.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_success.close_v_time
     *
     * @mbggenerated
     */
    private Date closeVTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_success.contract_numbe
     *
     * @mbggenerated
     */
    private String contractNumbe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_success.class_hour
     *
     * @mbggenerated
     */
    private Integer classHour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_success.order_money
     *
     * @mbggenerated
     */
    private BigDecimal orderMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_success.gift
     *
     * @mbggenerated
     */
    private String gift;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_success.pay_status
     *
     * @mbggenerated
     */
    private String payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_success.c_time
     *
     * @mbggenerated
     */
    private Date cTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_success.pay_time
     *
     * @mbggenerated
     */
    private Date payTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_success.id
     *
     * @return the value of hf_success.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_success.id
     *
     * @param id the value for hf_success.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_success.order_id
     *
     * @return the value of hf_success.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_success.order_id
     *
     * @param orderId the value for hf_success.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_success.close_v_time
     *
     * @return the value of hf_success.close_v_time
     *
     * @mbggenerated
     */
    public Date getCloseVTime() {
        return closeVTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_success.close_v_time
     *
     * @param closeVTime the value for hf_success.close_v_time
     *
     * @mbggenerated
     */
    public void setCloseVTime(Date closeVTime) {
        this.closeVTime = closeVTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_success.contract_numbe
     *
     * @return the value of hf_success.contract_numbe
     *
     * @mbggenerated
     */
    public String getContractNumbe() {
        return contractNumbe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_success.contract_numbe
     *
     * @param contractNumbe the value for hf_success.contract_numbe
     *
     * @mbggenerated
     */
    public void setContractNumbe(String contractNumbe) {
        this.contractNumbe = contractNumbe == null ? null : contractNumbe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_success.class_hour
     *
     * @return the value of hf_success.class_hour
     *
     * @mbggenerated
     */
    public Integer getClassHour() {
        return classHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_success.class_hour
     *
     * @param classHour the value for hf_success.class_hour
     *
     * @mbggenerated
     */
    public void setClassHour(Integer classHour) {
        this.classHour = classHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_success.order_money
     *
     * @return the value of hf_success.order_money
     *
     * @mbggenerated
     */
    public BigDecimal getOrderMoney() {
        return orderMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_success.order_money
     *
     * @param orderMoney the value for hf_success.order_money
     *
     * @mbggenerated
     */
    public void setOrderMoney(BigDecimal orderMoney) {
        this.orderMoney = orderMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_success.gift
     *
     * @return the value of hf_success.gift
     *
     * @mbggenerated
     */
    public String getGift() {
        return gift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_success.gift
     *
     * @param gift the value for hf_success.gift
     *
     * @mbggenerated
     */
    public void setGift(String gift) {
        this.gift = gift == null ? null : gift.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_success.pay_status
     *
     * @return the value of hf_success.pay_status
     *
     * @mbggenerated
     */
    public String getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_success.pay_status
     *
     * @param payStatus the value for hf_success.pay_status
     *
     * @mbggenerated
     */
    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus == null ? null : payStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_success.c_time
     *
     * @return the value of hf_success.c_time
     *
     * @mbggenerated
     */
    public Date getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_success.c_time
     *
     * @param cTime the value for hf_success.c_time
     *
     * @mbggenerated
     */
    public void setcTime(Date cTime) {
        this.cTime = cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_success.pay_time
     *
     * @return the value of hf_success.pay_time
     *
     * @mbggenerated
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_success.pay_time
     *
     * @param payTime the value for hf_success.pay_time
     *
     * @mbggenerated
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }
}